SAD/SAD/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts import urls as u1
from doctor_calendar import urls as u2
from doctor_rating import urls as u3
from medicine_page import urls as u4
from prescription import urls as u5

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(u1)),
    path('', include(u2)),
    path('', include(u3)),
    path('', include(u4)),
    path('', include(u5)),
    path('accounts/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SAD/accounts/urls.py
from django.contrib.auth.decorators import login_required

from accounts import views as v
from django.conf.urls import url
from django.urls import path, include
from accounts.forms import UserSetPassword, UserPasswordChange
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('accounts/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             form_class=UserSetPassword), name='password_reset_confirm'),
    path('accounts/password_reset/',
         auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_change/',
        auth_views.PasswordChangeView.as_view(
            form_class=UserPasswordChange), name='password_change'),
    url(r'^profile/edit/$', v.edit_profile, name='edit_profile'),
    url(r'^register/$', v.register, name='register'),
    url(r'^user_login/$', v.user_login, name='user_login'),
    url(r'^logout/$', v.user_logout, name='logout'),
    url(r'^special/', v.special, name='special'),
    url(r'^$', v.index, name='index'),
    url(r'^mini_profile/(?P<pk>\d+)$', v.mini_profile, name='mini_profile'),
    url(r'monthly_income$', v.monthly_income, name='monthly_income'),
    url(r'^search_page/', v.doctor_search, name='search_page'),
    url(r'^list/', login_required(v.PatientListView.as_view()), name='list'),
    url(r'^visit_history/', v.DoctorListView.as_view(), name='history'),
    url(r'^lang/(?P<en>\d+)$', v.change_lang, name='change_lang')

]

SAD/doctor_rating/urls.py
from django.conf.urls import url

import doctor_rating.views as v

app_name = 'doctor_rating'
urlpatterns = [
    url(r'^rate/', v.rate, name='rate'),
]

SAD/prescription/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from prescription import views as v

app_name = 'prescription'
urlpatterns = [
    url(r'^prescription/(?P<prescription_id>\d+)/(?P<cal>\d+)/$', v.write_prescription, name='prescription'),
    url(r'prescription/(?P<prescription_id>\d+)/(?P<cal>\d+)/delete-med/(?P<med_id>\d+)/(?P<med_type>\d+)', v.delete_med, name='delete-med'),
    url(r'^make-prescription/(?P<doc_id>\d+)/(?P<patient_id>\d+)/(?P<event_id>\d+)$', v.make_prescription,
        name='make-prescription'),
    url(r'^prescription_list/(?P<pk>\d+)', login_required(v.PrescriptionListView.as_view()), name='pre_list'),
    url(r'^prescription_list_patient/(?P<pk>\d+)', login_required(v.PrescriptionListPatientView.as_view()),
        name='pre_list_patient')

]

SAD/templates/visit_history/history.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block body_block %}
    <link rel="stylesheet" href="{% static 'css/search_result.css' %}" type="text/css">
{% language request.session.lang %}
    {% get_current_language as LANGUAGE_CODE %}
    <div class="container" id="search-container">
        {% if doctors.count == 0 %}
            <div class="jumbotron border">
                <p class="text"> {% trans 'ویزیتی وجود ندارد.' %}</p>
            </div>
        {% else %}
    {% for doctor in doctors %}
        <ul>
            <div class="jumbotron" id="search-jumbotron">
                <li>
                    <a href="{% url 'accounts:mini_profile' doctor.user.pk %}"> {{ doctor.user.name }} {{ doctor.user.family_name }}</a>
                    {% if doctor.user.doctorprofileinfo.profile_pic %}
                        <img src="{{ doctor.user.doctorprofileinfo.profile_pic.url }}" width="120" height="120">
                    {% else %}
                        {{ doctor.doctorprofileinfo.profile_pic.url }}
                        <img src="{% static 'default/default_8.jpg' %}" width="120" height="120">
                    {% endif %}
                            <form method="post">
                                {% csrf_token %}
                                <div>
                                    <div class="rateYo" id="{{doctor.user.pk}}">
                                    </div>
                                </div>
                             </form>
                    <br/>
                    <a class="btn btn-info" href="{% url 'prescription:pre_list_patient' doctor.user.pk%}">{% trans 'مشاهده نسخه‌ها' %}</a>
                </li>
            </div>
        </ul>
    {% endfor %}
                    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
                    <link href="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.css" rel="stylesheet"/>
                    <script src="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.js"></script>
                    <script>
                        $(document).ready(function(){
                        $(".rateYo").rateYo({
                            halfStar: true,
                            rating: 0,
                            numStars:5,
                            minValue:0,
                            maxValue:5,
                            normalFill: 'gray',
                            ratedFill: 'yellow',
                            starWidth: "25px",
                        });
                        $(".rateYo").rateYo().on('rateyo.set',function(e, data){
                            var id = jQuery(this).attr("id");
                            $.ajax({
                                url: "{% url 'doctor_rating:rate' %}",
                                type: 'POST',
                                data: {'rating': data.rating, 'doctor': id, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                                success: function() {
                                    if(confirm("{% trans 'با تشکر از رأی شما :)' %}")){
                                        window.location.reload();
                                    }
                                }
                            });
                            });
                        });
                    </script>
{% endif %}
</div>
 {% endlanguage %}
{% endblock %}