SAD/SAD/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts import urls as u1
from doctor_calendar import urls as u2
from doctor_rating import urls as u3
from medicine_page import urls as u4
from prescription import urls as u5

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(u1)),
    path('', include(u2)),
    path('', include(u3)),
    path('', include(u4)),
    path('', include(u5)),
    path('accounts/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SAD/accounts/urls.py
from django.contrib.auth.decorators import login_required

from accounts import views as v
from django.conf.urls import url
from django.urls import path, include
from accounts.forms import UserSetPassword, UserPasswordChange
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('accounts/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             form_class=UserSetPassword), name='password_reset_confirm'),
    path('accounts/password_reset/',
         auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_change/',
        auth_views.PasswordChangeView.as_view(
            form_class=UserPasswordChange), name='password_change'),
    url(r'^profile/edit/$', v.edit_profile, name='edit_profile'),
    url(r'^register/$', v.register, name='register'),
    url(r'^user_login/$', v.user_login, name='user_login'),
    url(r'^logout/$', v.user_logout, name='logout'),
    url(r'^special/', v.special, name='special'),
    url(r'^$', v.index, name='index'),
    url(r'^mini_profile/(?P<pk>\d+)$', v.mini_profile, name='mini_profile'),
    url(r'monthly_income$', v.monthly_income, name='monthly_income'),
    url(r'^search_page/', v.doctor_search, name='search_page'),
    url(r'^list/', login_required(v.PatientListView.as_view()), name='list'),
    url(r'^visit_history/', v.DoctorListView.as_view(), name='history'),
    url(r'^lang/(?P<en>\d+)$', v.change_lang, name='change_lang')

]

SAD/prescription/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from prescription import views as v

app_name = 'prescription'
urlpatterns = [
    url(r'^prescription/(?P<prescription_id>\d+)/(?P<cal>\d+)/$', v.write_prescription, name='prescription'),
    url(r'prescription/(?P<prescription_id>\d+)/(?P<cal>\d+)/delete-med/(?P<med_id>\d+)/(?P<med_type>\d+)', v.delete_med, name='delete-med'),
    url(r'^make-prescription/(?P<doc_id>\d+)/(?P<patient_id>\d+)/(?P<event_id>\d+)$', v.make_prescription,
        name='make-prescription'),
    url(r'^prescription_list/(?P<pk>\d+)', login_required(v.PrescriptionListView.as_view()), name='pre_list'),
    url(r'^prescription_list_patient/(?P<pk>\d+)', login_required(v.PrescriptionListPatientView.as_view()),
        name='pre_list_patient')

]

SAD/templates/patient_list/list.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block body_block %}
    <link rel="stylesheet" href="{% static "css/search_result.css" %}" type="text/css">
{% language request.session.lang %}
    {% get_current_language as LANGUAGE_CODE %}
    <div class="container" id="search-container">
        {% if patients.count == 0 %}
            <div class="jumbotron border">
                <p class="text">{% trans ' بیماری وجود ندارد.' %}</p>
            </div>
        {% else %}
    {% for patient in patients %}
        <ul>
            <div class="jumbotron" id="search-jumbotron">
                <li>
                    <a href="{% url 'accounts:mini_profile' patient.user.pk %}"> {{ patient.user.name }} {{ patient.user.family_name }}</a>
                    {% if patient.user.patientprofileinfo.profile_pic %}
                        <img src="{{ patient.user.patientprofileinfo.profile_pic.url }}" width="120" height="120">
                    {% else %}
                        <img src="{% static 'default/default_8.jpg' %}" width="120" height="120">
                    {% endif %}
                    <br/>
                    <a class="btn btn-info" href="{% url 'prescription:pre_list' patient.user.pk%}">{% trans 'مشاهده نسخه‌ها' %}</a>
                </li>
            </div>
            <div/>
        </ul>
    {% endfor %}
        {% endif %}
    </div>
     {% endlanguage %}
{% endblock %}