SAD/SAD/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts import urls as u1
from doctor_calendar import urls as u2
from doctor_rating import urls as u3
from medicine_page import urls as u4
from prescription import urls as u5

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(u1)),
    path('', include(u2)),
    path('', include(u3)),
    path('', include(u4)),
    path('', include(u5)),
    path('accounts/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SAD/accounts/urls.py
from django.contrib.auth.decorators import login_required

from accounts import views as v
from django.conf.urls import url
from django.urls import path, include
from accounts.forms import UserSetPassword, UserPasswordChange
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('accounts/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             form_class=UserSetPassword), name='password_reset_confirm'),
    path('accounts/password_reset/',
         auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_change/',
        auth_views.PasswordChangeView.as_view(
            form_class=UserPasswordChange), name='password_change'),
    url(r'^profile/edit/$', v.edit_profile, name='edit_profile'),
    url(r'^register/$', v.register, name='register'),
    url(r'^user_login/$', v.user_login, name='user_login'),
    url(r'^logout/$', v.user_logout, name='logout'),
    url(r'^special/', v.special, name='special'),
    url(r'^$', v.index, name='index'),
    url(r'^mini_profile/(?P<pk>\d+)$', v.mini_profile, name='mini_profile'),
    url(r'monthly_income$', v.monthly_income, name='monthly_income'),
    url(r'^search_page/', v.doctor_search, name='search_page'),
    url(r'^list/', login_required(v.PatientListView.as_view()), name='list'),
    url(r'^visit_history/', v.DoctorListView.as_view(), name='history'),
    url(r'^lang/(?P<en>\d+)$', v.change_lang, name='change_lang')

]

SAD/doctor_calendar/urls.py
from django.conf.urls import url

from doctor_calendar import views as v

app_name = 'doctor_calendar'
urlpatterns = [
    url(r'^calendar/(?P<pk>\d+)/(?P<week_num>\d+)$', v.PatientCalendarView.as_view(), name='calendar'),
    url(r'^calendar-next/(?P<pk>\d+)/(?P<week_num>\d+)$', v.next_week, name='calendar-next'),
    url(r'^calendar-next/(?P<week_num>\d+)$', v.doctor_next_week, name='doctor-calendar-next'),
    url(r'^schedule/(?P<week_num>\d+)$', v.DoctorCalenderView.as_view(), name='schedule'),
    url(r'^verify/(?P<pk>\d+)/(?P<week_num>\d+)$', v.VerifyView.as_view(), name='verify'),
    url(r'^calendar/(?P<doc_pk>\d+)/cancel/(?P<usr_pk>\d+)/(?P<evt_pk>\d+)$', v.cancel, name='cancel-appointment'),

]

SAD/templates/calendar/calendar.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block body_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/calendar.css' %}">
{% language request.session.lang %}
    {% get_current_language as LANGUAGE_CODE %}
    <script type="text/javascript" src="{% static 'scripts/cancel_appointment.js' %}"></script>
    <script type="text/javascript">
        function tdclick(dateAndTime) {
            if (confirm("{% trans 'آیا مطمئن هستید که میخواهید این زمان را رزرو کنید؟' %}")) {
                var form = $('<form></form>');
                form.attr("method", "GET");
                form.attr("action", "{% url 'doctor_calendar:verify' doctor 0%}");

                var field = $('<input></input>');
                field.attr("type", "hidden");
                field.attr("name", "q1");
                field.attr("value", dateAndTime);

                form.append(field);
                $(document.body).append(form);
                form.submit();


            }

        }

        function myAlert() {
            alert("{% trans 'از زمان رزرو این ساعت گذشته است!' %}");
        }
    </script>
    <div class="jumbotron" id="search-jumbotron">

        <div class="clearfix">
            <a class="btn btn-info left" href="{% url 'doctor_calendar:calendar-next' doctor 2 %} "> {% trans 'هفته قبل'%} </a>
            <a class="btn btn-info right" href="{% url 'doctor_calendar:calendar-next' doctor 1 %}"> {% trans 'هفته بعد' %} </a>
        </div>
        <div id="calendar-div">
        {{ calendar }}
        </div>
    </div>
{% endlanguage %}
{% endblock %}

SAD/templates/calendar/doctor_calender.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block body_block %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/calendar.css' %}">
{% language request.session.lang %}
    {% get_current_language as LANGUAGE_CODE %}
    <div class="jumbotron" id="search-jumbotron">

    <div class="clearfix">
        <a class="btn btn-info left" href="{% url 'doctor_calendar:doctor-calendar-next' 2 %} "> {% trans 'هفته قبل'%} </a>
        <a class="btn btn-info right" href="{% url 'doctor_calendar:doctor-calendar-next' 1 %}"> {% trans 'هفته بعد' %} </a>
    </div>
    <div id="calendar-div">
        {{ calendar }}
    </div>

    </div>

{% endlanguage %}
{% endblock %}

SAD/templates/calendar/verify.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block body_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/calendar.css' %}">
{% language request.session.lang %}
    {% get_current_language as LANGUAGE_CODE %}
    <div class="jumbotron" id="search-jumbotron">
{#        <div class="clearfix">#}
{#            {{ calendar }}#}
{#        </div>#}
        <div class="clearfix">
                {% if success is True %}
                    <p> {% trans 'رزرو و پرداخت موفقیت آمیز بود' %}</p>
                    <br>
                    <p> {% trans 'نام دکتر'%} : {{ name }} {{ lname }}</p>
                    <br>
                    <p> {% trans 'تاریخ رزرو شما'%} : {{ day }}/ {{ month }}/ {{ year }}</p>
                    <br>
                    <p> {% trans 'ساعت رزرو'%} : {{ hour }}</p>
                    <br>
                    <p> {% trans 'آدرس مطب'%} : {{ address }}</p>
                {% else %}
                    <p> {% trans 'موجودی کافی نیست.لطفا اقدام به افزایش موجودی خود کنید'%}</p>
{#                    <p>  {{  address }} </p>#}
                {% endif %}

            <a class="btn btn-info left" href="{% url 'accounts:index' %} "> {% trans 'بازگشت به صفحه پروفایل'%} </a>
            <a class="btn btn-info right" href={{request.META.HTTP_REFERER}}> {% trans 'بازگشت به صفحه رزرو'%} </a>
        </div>
    </div>
{% endlanguage %}
{% endblock %}