SAD/SAD/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts import urls as u1
from doctor_calendar import urls as u2
from doctor_rating import urls as u3
from medicine_page import urls as u4
from prescription import urls as u5

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(u1)),
    path('', include(u2)),
    path('', include(u3)),
    path('', include(u4)),
    path('', include(u5)),
    path('accounts/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SAD/accounts/urls.py
from django.contrib.auth.decorators import login_required

from accounts import views as v
from django.conf.urls import url
from django.urls import path, include
from accounts.forms import UserSetPassword, UserPasswordChange
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('accounts/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             form_class=UserSetPassword), name='password_reset_confirm'),
    path('accounts/password_reset/',
         auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_change/',
        auth_views.PasswordChangeView.as_view(
            form_class=UserPasswordChange), name='password_change'),
    url(r'^profile/edit/$', v.edit_profile, name='edit_profile'),
    url(r'^register/$', v.register, name='register'),
    url(r'^user_login/$', v.user_login, name='user_login'),
    url(r'^logout/$', v.user_logout, name='logout'),
    url(r'^special/', v.special, name='special'),
    url(r'^$', v.index, name='index'),
    url(r'^mini_profile/(?P<pk>\d+)$', v.mini_profile, name='mini_profile'),
    url(r'monthly_income$', v.monthly_income, name='monthly_income'),
    url(r'^search_page/', v.doctor_search, name='search_page'),
    url(r'^list/', login_required(v.PatientListView.as_view()), name='list'),
    url(r'^visit_history/', v.DoctorListView.as_view(), name='history'),
    url(r'^lang/(?P<en>\d+)$', v.change_lang, name='change_lang')

]

SAD/templates/base.html
<!DOCTYPE html>
{% load static %}
{% if request.session.lang == "fa" %}
    <html dir="rtl" lang="fa" translate="yes">
{% else %}
    <html lang="" translate="yes">
{% endif %}
<head>
    <meta charset="utf-8" >
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>پزشکات</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css"/>

    <link rel="stylesheet" href="{% static "admin/css/forms.css" %}" type="text/css">
    <link rel="stylesheet" href="{% static "admin/css/base.css" %}" type="text/css">

    <link rel="stylesheet" href="{% static "css/basics.css" %}" type="text/css">
    {% if request.session.lang == 'en' %}
    <style>
        *{
            font-family: "Sakkal Majalla", serif;
        font-size: medium;
    }</style>
    {% endif %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
            integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
            integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
            crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>


</head>
<body>

<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
<script src="{% static 'scripts/toggler.js' %}"></script>

<nav class="navbar navbar-default navbar-fixed-top navbar-static-top" role="navigation">

    <div class="container">

        <button class="navbar-toggler navbar-left button " data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="True" aria-label="Toggle navigation"> ☰
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse " id="navbarCollapse">

            {% if request.session.lang == "fa" %}
                <ul class="nav navbar-nav navbar-right ">
            {% else %}
                <ul class="nav navbar-nav ">
            {% endif %}
            {% if not user.is_authenticated %}
                {% if request.session.lang == "en" %}
                    <li><a class="navbar-link " id="brand" href="{% url 'accounts:index' %}">Doctors</a></li>
                    <li><a class="navbar-link " href="{% url 'accounts:user_login' %}">Login</a></li>
                {% endif %}
                <li class="dropdown show navbar-item ">
                    {% if request.session.lang == "fa" %}
                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            ثبت نام
                        </a>
                    {% else %}

                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Register
                        </a>
                    {% endif %}

                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" dir="rtl">
                        {% if request.session.lang == "fa" %}
                            <ul><a class="dropdown-item" href="/register/?id=1" dir="rtl" lang="fa">به عنوان
                                پزشک</a>
                            </ul>
                            <ul><a class="dropdown-item" href="/register/?id=2" dir="rtl" lang="fa">به عنوان
                                بیمار</a>
                            </ul>
                        {% else %}
                            <ul><a class="dropdown-item" href="/register/?id=1" dir="rtl" lang="fa">As &nbsp; a &nbsp;
                                Doctor</a>
                            </ul>
                            <ul><a class="dropdown-item" href="/register/?id=2" dir="rtl" lang="fa">As &nbsp; a &nbsp;
                                Patient</a>
                            </ul>
                        {% endif %}
                    </div>
                </li>
                {% if request.session.lang == "fa" %}

                    <li><a class="navbar-link " href="{% url 'accounts:user_login' %}">ورود</a></li>
                    <li><a class="navbar-link " id="brand" href="{% url 'accounts:index' %}">پزشکات</a></li>

                {% endif %}
            {% endif %}
            {% if user.is_authenticated %}
                {% if request.session.lang == "fa" %}
                    <li><a class="navbar-link" href="{% url 'accounts:logout' %}">خروج</a></li>
                    <li><a class="navbar-link" href="{% url 'accounts:search_page' %}">جست‌وجوی
                        پزشک</a></li>

                    {% if user.is_doctor %}
                        <li><a class="navbar-link" href="{% url 'accounts:index' %}"><img class="nav_img"
                                                                                          src="{{ user.doctorprofileinfo.profile_pic.url }}"/></a>
                        </li>
                    {% else %}
                        <li><a class="navbar-link" href="{% url 'accounts:index' %}"><img class="nav_img"
                                                                                          src="{{ user.patientprofileinfo.profile_pic.url }}"/></a>
                        </li>
                    {% endif %}
                {% else %}
                    {% if user.is_doctor %}
                        <li><a class="navbar-link" href="{% url 'accounts:index' %}"><img class="nav_img"
                                                                                          src="{{ user.doctorprofileinfo.profile_pic.url }}"/></a>
                        </li>
                    {% else %}
                        <li><a class="navbar-link" href="{% url 'accounts:index' %}"><img class="nav_img"
                                                                                          src="{{ user.patientprofileinfo.profile_pic.url }}"/></a>
                        </li>
                    {% endif %}
                    <li><a class="navbar-link" href="{% url 'accounts:search_page' %}">Search Doctors</a></li>
                    <li><a class="navbar-link" href="{% url 'accounts:logout' %}">Exit</a></li>
                {% endif %}
            {% endif %}


            </ul>

            <!--                {% if user.is_authenticated %}-->
                <!--                    <li><a class="navbar-link" href="{% url 'accounts:logout' %}">خروج</a></li>-->
                <!--                {% endif %}-->

            {% if request.session.lang == "fa" %}
                <ul class="navbar-nav ml-auto">
            {% else %}
                <ul class="navbar-nav ml-auto navbar-right">
            {% endif %}
            <li style="margin: 3px; list-style: none"><a style="float: left !important; font-size: small"
                                                         class="navbar-link"
                                                         href="{% url 'accounts:change_lang' 1 %}">English</a></li>
            <li style="margin: 3px; list-style: none"><a style="float: left !important; font-size: small"
                                                         class="navbar-link"
                                                         href="{% url 'accounts:change_lang' 0 %}">فارسی</a></li>
            </ul>
        </div>
    </div>

</nav>
<div class="container">
    {% block body_block %}
    {% endblock %}
</div>
</body>
</html>